apiVersion: release.giantswarm.io/v1alpha1
kind: Release
metadata:
  name: aks-35.0.0
spec:
  apps:
    - name: cert-exporter
      catalog: default
      version: 2.11.0
      dependsOn:
        - kyverno-crds
    - name: cert-manager
      catalog: default
      version: 3.13.0
      dependsOn:
        - alloy-logs
        - prometheus-operator-crd
    - name: chart-operator-extensions
      catalog: default
      version: 1.1.3
      dependsOn:
        - prometheus-operator-crd
    - name: cilium-servicemonitors
      catalog: default
      version: 0.1.4
      dependsOn:
        - prometheus-operator-crd
    - name: azure-aks-extras
      catalog: default
      version: 0.1.0
    - name: external-dns
      catalog: default
      version: 3.5.0
      dependsOn:
        - prometheus-operator-crd
    - name: k8s-audit-metrics
      catalog: default
      version: 0.10.13
      dependsOn:
        - kyverno-crds
    - name: k8s-dns-node-cache
      catalog: default
      version: 2.11.0
      dependsOn:
        - kyverno-crds
    - name: net-exporter
      catalog: default
      version: 1.24.0
      dependsOn:
        - prometheus-operator-crd
    - name: network-policies
      catalog: cluster
      version: 0.2.0
    - name: node-exporter
      catalog: default
      version: 1.20.11
      dependsOn:
        - kyverno-crds
    - name: observability-bundle
      catalog: default
      version: 2.9.1
    - name: observability-policies
      catalog: default
      version: 0.0.4
      dependsOn:
        - kyverno-crds
    - name: priority-classes
      catalog: default
      version: 0.3.1
    - name: prometheus-blackbox-exporter
      catalog: default
      version: 0.8.0
      dependsOn:
        - prometheus-operator-crd
    - name: rbac-bootstrap
      version: 0.3.0
    - name: security-bundle
      catalog: giantswarm
      version: 1.17.1
      dependsOn:
        - prometheus-operator-crd
    - name: teleport-kube-agent
      catalog: default
      version: 0.11.1
      dependsOn:
        - prometheus-operator-crd
    - name: vertical-pod-autoscaler
      catalog: default
      version: 6.1.2
      dependsOn:
        - prometheus-operator-crd
    - name: vertical-pod-autoscaler-crd
      catalog: default
      version: 4.1.2
  components:
    - name: cluster-aks
      catalog: cluster
      version: 0.1.0
    - name: kubernetes
      catalog: control-plane-catalog
      version: 1.35.5
  date: "2026-06-18T16:37:01Z"
  state: active
