resources:
- release.yaml

replacements:
- source:
    group: release.giantswarm.io
    kind: Release
    fieldPath: metadata.name
    options:
      delimiter: "-"
      # Need to target index 2 here as `cloud-director` itself already contains a hyphen.
      index: 2
  targets:
  - select:
      group: release.giantswarm.io
      kind: Release
    fieldPaths:
    - metadata.annotations.[giantswarm.io/release-notes]
    options:
      create: true
