apiVersion: release.giantswarm.io/v1alpha1
kind: Release
metadata:
  creationTimestamp: null
  name: v11.3.3
spec:
  apps:
  - name: cert-exporter
    version: 1.2.1
  - componentVersion: 0.9.0
    name: cert-manager
    version: 1.0.8
  - name: chart-operator
    version: 0.12.4
  - componentVersion: 1.16.2
    name: cluster-autoscaler
    version: 1.1.4
  - componentVersion: 1.6.5
    name: coredns
    version: 1.1.8
  - componentVersion: 0.5.18
    name: external-dns
    version: 1.2.1
  - componentVersion: 3.5.0
    name: kiam
    version: 1.2.2
  - componentVersion: 1.9.5
    name: kube-state-metrics
    version: 1.0.5
  - componentVersion: 0.3.3
    name: metrics-server
    version: 1.0.0
  - name: net-exporter
    version: 1.7.0
  - componentVersion: 0.18.1
    name: node-exporter
    version: 1.2.0
  components:
  - name: app-operator
    version: 1.0.0
  - name: aws-cni
    version: 1.6.0
  - name: aws-operator
    version: 8.6.1
  - name: calico
    version: 3.10.1
  - name: cert-operator
    version: 0.1.0
  - name: cluster-operator
    version: 2.2.0
  - name: containerlinux
    version: 2345.3.1
  - name: etcd
    version: 3.3.17
  - name: kubernetes
    version: 1.16.9
  date: "2020-06-05T15:00:00Z"
  state: active
