name: 'Create Controller Readiness Issues'
description: 'Creates controller readiness tracking issues for major releases and posts tracking comments on PRs'
inputs:
  providers:
    description: 'Space-separated list of providers included in the release (e.g. "aws azure vsphere")'
    required: true
  version:
    description: 'Release version (e.g. v35.0.0)'
    required: true
  pr_numbers:
    description: 'Comma-separated list of PR numbers to post tracking comments on'
    required: true
  github_token:
    description: 'GitHub token for API access'
    required: true
  project_token:
    description: 'GitHub token with project write permissions (for adding issues to GitHub Projects)'
    required: false
    default: ''
runs:
  using: "composite"
  steps:
    - name: Create readiness issues and post tracking comments
      shell: bash
      env:
        GH_TOKEN: ${{ inputs.github_token }}
        PROJECT_TOKEN: ${{ inputs.project_token }}
        PROVIDERS: ${{ inputs.providers }}
        VERSION: ${{ inputs.version }}
        PR_NUMBERS: ${{ inputs.pr_numbers }}
      run: |
        echo "=== Controller Readiness Issue Creation ==="
        echo "Providers: $PROVIDERS"
        echo "Version: $VERSION"
        echo "PR numbers: $PR_NUMBERS"

        # Map providers to teams and their controller apps
        # EKS is excluded (no cloud controller manager)
        declare -A TEAM_PROVIDERS
        declare -A TEAM_LABELS
        declare -A TEAM_PROJECT_NAME

        for provider in $PROVIDERS; do
          case "$provider" in
            aws)
              TEAM_PROVIDERS["team-phoenix"]+="aws "
              TEAM_LABELS["team-phoenix"]="team/phoenix"
              TEAM_PROJECT_NAME["team-phoenix"]="Phoenix"
              ;;
            azure)
              TEAM_PROVIDERS["team-phoenix"]+="azure "
              TEAM_LABELS["team-phoenix"]="team/phoenix"
              TEAM_PROJECT_NAME["team-phoenix"]="Phoenix"
              ;;
            vsphere)
              TEAM_PROVIDERS["team-rocket"]+="vsphere "
              TEAM_LABELS["team-rocket"]="team/rocket"
              TEAM_PROJECT_NAME["team-rocket"]="Rocket"
              ;;
            cloud-director)
              TEAM_PROVIDERS["team-rocket"]+="cloud-director "
              TEAM_LABELS["team-rocket"]="team/rocket"
              TEAM_PROJECT_NAME["team-rocket"]="Rocket"
              ;;
            eks)
              echo "Skipping EKS - no cloud controller manager needed"
              ;;
          esac
        done

        if [[ ${#TEAM_PROVIDERS[@]} -eq 0 ]]; then
          echo "No teams require controller readiness issues (only EKS providers). Skipping."
          exit 0
        fi

        # Ensure required labels exist in giantswarm/roadmap
        gh label create "controller-readiness" --repo giantswarm/roadmap \
          --description "Controller app readiness tracking for major releases" \
          --color "C2E0C6" 2>/dev/null || echo "Label 'controller-readiness' already exists."

        RELEASE_LABEL="release/$VERSION"
        gh label create "$RELEASE_LABEL" --repo giantswarm/roadmap \
          --description "Related to release $VERSION" \
          --color "1D76DB" 2>/dev/null || echo "Label '$RELEASE_LABEL' already exists."

        # Helper: get display name for a provider (e.g. "aws" -> "AWS")
        provider_display_name() {
          case "$1" in
            aws) echo "AWS" ;;
            azure) echo "Azure" ;;
            vsphere) echo "vSphere" ;;
            cloud-director) echo "Cloud Director" ;;
            *) echo "$1" ;;
          esac
        }

        # Helper: build checklist items for a given provider
        checklist_for_provider() {
          local p="$1"
          case "$p" in
            aws)
              echo "- [ ] \`cloud-provider-aws\` — updated for Kubernetes in $VERSION"
              ;;
            azure)
              echo "- [ ] \`azure-cloud-controller-manager\` — updated for Kubernetes in $VERSION"
              echo "- [ ] \`azure-cloud-node-manager\` — updated for Kubernetes in $VERSION"
              ;;
            vsphere)
              echo "- [ ] \`cloud-provider-vsphere\` — updated for Kubernetes in $VERSION"
              ;;
            cloud-director)
              echo "- [ ] \`cloud-provider-cloud-director\` — updated for Kubernetes in $VERSION"
              ;;
          esac
        }

        # Build tracking table rows
        TRACKING_ROWS=""

        for team in "${!TEAM_PROVIDERS[@]}"; do
          providers_list=$(echo "${TEAM_PROVIDERS[$team]}" | xargs | tr ' ' ', ')
          team_label="${TEAM_LABELS[$team]}"

          # Build display name list for titles (e.g. "AWS, Azure")
          providers_display=""
          for provider in ${TEAM_PROVIDERS[$team]}; do
            if [[ -n "$providers_display" ]]; then
              providers_display+=", "
            fi
            providers_display+="$(provider_display_name "$provider")"
          done

          echo "--- Processing $team (providers: $providers_display) ---"

          # Build controller app checklist
          CHECKLIST=""
          for provider in ${TEAM_PROVIDERS[$team]}; do
            CHECKLIST+="$(checklist_for_provider "$provider")"$'\n'
          done

          # Check for existing issue (deduplication for re-runs and individual matrix runs)
          EXISTING_ISSUE=$(gh issue list --repo giantswarm/roadmap \
            --label "controller-readiness" --label "$team_label" --label "$RELEASE_LABEL" \
            --state open \
            --json number --jq '.[0].number')

          if [[ -n "$EXISTING_ISSUE" ]]; then
            echo "Found existing issue #$EXISTING_ISSUE for $team."
            ISSUE_NUMBER="$EXISTING_ISSUE"
            ISSUE_URL="https://github.com/giantswarm/roadmap/issues/$EXISTING_ISSUE"

            # Check if the current provider's apps are already listed (handles individual matrix runs
            # where aws creates the issue, then azure runs and finds it but azure apps are missing)
            EXISTING_BODY=$(gh issue view "$EXISTING_ISSUE" --repo giantswarm/roadmap --json body --jq '.body')
            NEEDS_UPDATE=false
            for provider in ${TEAM_PROVIDERS[$team]}; do
              ITEMS="$(checklist_for_provider "$provider")"
              # Check if any checklist item from this provider is missing
              FIRST_ITEM=$(echo "$ITEMS" | head -1)
              if ! echo "$EXISTING_BODY" | grep -qF "$FIRST_ITEM"; then
                NEEDS_UPDATE=true
                break
              fi
            done

            if [[ "$NEEDS_UPDATE" == "true" ]]; then
              echo "Updating issue #$EXISTING_ISSUE to include apps for: $providers_display"
              # Rebuild the entire body with the complete checklist
              ISSUE_TITLE="Controller readiness: $providers_display Release $VERSION"
              UPDATED_BODY="## Controller Readiness for Release $VERSION

        The major release **$VERSION** has been created. The following cloud controller apps need new versions compatible with the Kubernetes version in this release.

        ### Apps to update

        ${CHECKLIST}
        ### Context

        - Release PR: [giantswarm/releases#${PR_NUMBERS}](https://github.com/giantswarm/releases/pull/${PR_NUMBERS})
        - Once all items are checked off and this issue is closed, the release PR will automatically receive a component bump to pick up the new controller versions."

              gh issue edit "$EXISTING_ISSUE" --repo giantswarm/roadmap \
                --title "$ISSUE_TITLE" \
                --body "$UPDATED_BODY"
              echo "Updated issue #$EXISTING_ISSUE"
            else
              echo "Issue #$EXISTING_ISSUE already has all apps listed. No update needed."
            fi
          else
            ISSUE_TITLE="Controller readiness: $providers_display Release $VERSION"

            ISSUE_BODY="## Controller Readiness for Release $VERSION

        The major release **$VERSION** has been created. The following cloud controller apps need new versions compatible with the Kubernetes version in this release.

        ### Apps to update

        ${CHECKLIST}
        ### Context

        - Release PR: [giantswarm/releases#${PR_NUMBERS}](https://github.com/giantswarm/releases/pull/${PR_NUMBERS})
        - Once all items are checked off and this issue is closed, the release PR will automatically receive a component bump to pick up the new controller versions."

            ISSUE_URL=$(gh issue create --repo giantswarm/roadmap \
              --title "$ISSUE_TITLE" \
              --body "$ISSUE_BODY" \
              --label "controller-readiness" --label "$team_label" --label "$RELEASE_LABEL")

            ISSUE_NUMBER=$(echo "$ISSUE_URL" | grep -oE '[0-9]+$')
            echo "Created issue $ISSUE_URL"

            # Add the issue to GitHub Project #273 (Roadmap board) and set Team field.
            # Uses a separate PROJECT_TOKEN (ISSUE_AUTOMATION) with project write permissions.
            # The default GH_TOKEN (TAYLORBOT_GITHUB_ACTION) lacks the 'project' scope.
            if [[ -z "$PROJECT_TOKEN" ]]; then
              echo "Warning: No project_token provided. Skipping project integration."
            else
              echo "Adding issue to project #273 and setting Team field..."
              team_project_name="${TEAM_PROJECT_NAME[$team]}"

              # Step 1: Get the issue's node ID
              ISSUE_NODE_ID=$(GH_TOKEN="$PROJECT_TOKEN" gh api graphql -f query='
                query($owner: String!, $repo: String!, $number: Int!) {
                  repository(owner: $owner, name: $repo) {
                    issue(number: $number) { id }
                  }
                }' -f owner="giantswarm" -f repo="roadmap" -F number="$ISSUE_NUMBER" \
                --jq '.data.repository.issue.id' 2>/dev/null || echo "")

              if [[ -z "$ISSUE_NODE_ID" ]]; then
                echo "Warning: Could not get issue node ID. Skipping project integration."
              else
                # Step 2: Add item to project
                ITEM_ID=$(GH_TOKEN="$PROJECT_TOKEN" gh api graphql -f query='
                  mutation($projectId: ID!, $contentId: ID!) {
                    addProjectV2ItemById(input: {projectId: $projectId, contentId: $contentId}) {
                      item { id }
                    }
                  }' -f projectId="PVT_kwDOAHNM9M4ABvWx" -f contentId="$ISSUE_NODE_ID" \
                  --jq '.data.addProjectV2ItemById.item.id' 2>/dev/null || echo "")

                if [[ -n "$ITEM_ID" ]]; then
                  echo "Added to project with item ID: $ITEM_ID"

                  # Step 3: Look up the Team option ID matching our team name
                  TEAM_OPTION_ID=$(GH_TOKEN="$PROJECT_TOKEN" gh api graphql -f query='
                    {
                      organization(login: "giantswarm") {
                        projectV2(number: 273) {
                          field(name: "Team") {
                            ... on ProjectV2SingleSelectField {
                              options { id name }
                            }
                          }
                        }
                      }
                    }' --jq ".data.organization.projectV2.field.options[] | select(.name | contains(\"$team_project_name\")) | .id" 2>/dev/null || echo "")

                  if [[ -n "$TEAM_OPTION_ID" ]]; then
                    # Step 4: Set the Team field
                    GH_TOKEN="$PROJECT_TOKEN" gh api graphql -f query='
                      mutation($projectId: ID!, $itemId: ID!, $fieldId: ID!, $optionId: String!) {
                        updateProjectV2ItemFieldValue(input: {
                          projectId: $projectId,
                          itemId: $itemId,
                          fieldId: $fieldId,
                          value: { singleSelectOptionId: $optionId }
                        }) { projectV2Item { id } }
                      }' -f projectId="PVT_kwDOAHNM9M4ABvWx" \
                         -f itemId="$ITEM_ID" \
                         -f fieldId="PVTSSF_lADOAHNM9M4ABvWxzgBApUw" \
                         -f optionId="$TEAM_OPTION_ID" 2>/dev/null \
                      && echo "Set Team field to $team_project_name" \
                      || echo "Warning: Could not set Team field"
                  else
                    echo "Warning: Could not find Team option matching '$team_project_name'"
                  fi
                else
                  echo "Warning: Could not add issue to project (check token permissions)"
                fi
              fi
            fi
          fi

          TRACKING_ROWS+="| $team | $providers_list | giantswarm/roadmap#$ISSUE_NUMBER | open |"$'\n'
        done

        # Post tracking comment on each release PR
        TRACKING_COMMENT="<!-- CONTROLLER_READINESS_START -->
        ## Controller readiness tracker

        | Team | Providers | Issue | Status |
        |------|-----------|-------|--------|
        ${TRACKING_ROWS}<!-- CONTROLLER_READINESS_END -->"

        IFS=',' read -ra PR_ARRAY <<< "$PR_NUMBERS"
        for pr_number in "${PR_ARRAY[@]}"; do
          pr_number=$(echo "$pr_number" | xargs) # trim whitespace
          if [[ -z "$pr_number" ]]; then
            continue
          fi

          echo "Posting tracking comment on PR #$pr_number..."

          # Check for existing tracking comment
          EXISTING_COMMENT_ID=$(gh api "repos/$GITHUB_REPOSITORY/issues/$pr_number/comments" --paginate \
            --jq '.[] | select(.body | contains("CONTROLLER_READINESS_START")) | .id' | head -1)

          if [[ -n "$EXISTING_COMMENT_ID" ]]; then
            echo "Updating existing tracking comment $EXISTING_COMMENT_ID on PR #$pr_number"
            gh api "repos/$GITHUB_REPOSITORY/issues/comments/$EXISTING_COMMENT_ID" \
              -X PATCH -f body="$TRACKING_COMMENT"
          else
            gh pr comment "$pr_number" --repo "$GITHUB_REPOSITORY" --body "$TRACKING_COMMENT"
          fi
        done

        echo "=== Controller readiness issue creation complete ==="
