name: 'Create Controller Readiness Issues'
description: 'Creates controller readiness tracking issues for major releases and posts tracking comments on PRs'
inputs:
  providers:
    description: 'Space-separated list of providers included in the release (e.g. "aws azure vsphere")'
    required: true
  version:
    description: 'Release version (e.g. v35.0.0)'
    required: true
  pr_numbers:
    description: 'Comma-separated list of PR numbers to post tracking comments on'
    required: true
  github_token:
    description: 'GitHub token for API access'
    required: true
runs:
  using: "composite"
  steps:
    - name: Create readiness issues and post tracking comments
      shell: bash
      env:
        GH_TOKEN: ${{ inputs.github_token }}
        PROVIDERS: ${{ inputs.providers }}
        VERSION: ${{ inputs.version }}
        PR_NUMBERS: ${{ inputs.pr_numbers }}
      run: |
        echo "=== Controller Readiness Issue Creation ==="
        echo "Providers: $PROVIDERS"
        echo "Version: $VERSION"
        echo "PR numbers: $PR_NUMBERS"

        # Map providers to teams and their controller apps
        # EKS is excluded (no cloud controller manager)
        declare -A TEAM_PROVIDERS
        declare -A TEAM_LABELS
        declare -A TEAM_PROJECT_FIELD

        for provider in $PROVIDERS; do
          case "$provider" in
            aws)
              TEAM_PROVIDERS["team-phoenix"]+="aws "
              TEAM_LABELS["team-phoenix"]="team/phoenix"
              TEAM_PROJECT_FIELD["team-phoenix"]="Phoenix 🔥"
              ;;
            azure)
              TEAM_PROVIDERS["team-phoenix"]+="azure "
              TEAM_LABELS["team-phoenix"]="team/phoenix"
              TEAM_PROJECT_FIELD["team-phoenix"]="Phoenix 🔥"
              ;;
            vsphere)
              TEAM_PROVIDERS["team-rocket"]+="vsphere "
              TEAM_LABELS["team-rocket"]="team/rocket"
              TEAM_PROJECT_FIELD["team-rocket"]="Rocket 🚀"
              ;;
            cloud-director)
              TEAM_PROVIDERS["team-rocket"]+="cloud-director "
              TEAM_LABELS["team-rocket"]="team/rocket"
              TEAM_PROJECT_FIELD["team-rocket"]="Rocket 🚀"
              ;;
            eks)
              echo "Skipping EKS - no cloud controller manager needed"
              ;;
          esac
        done

        if [[ ${#TEAM_PROVIDERS[@]} -eq 0 ]]; then
          echo "No teams require controller readiness issues (only EKS providers). Skipping."
          exit 0
        fi

        # Ensure the controller-readiness label exists in giantswarm/roadmap
        gh label create "controller-readiness" --repo giantswarm/roadmap \
          --description "Controller app readiness tracking for major releases" \
          --color "C2E0C6" 2>/dev/null || echo "Label 'controller-readiness' already exists."

        # Build tracking table rows
        TRACKING_ROWS=""

        for team in "${!TEAM_PROVIDERS[@]}"; do
          providers_list=$(echo "${TEAM_PROVIDERS[$team]}" | xargs | tr ' ' ', ')
          team_label="${TEAM_LABELS[$team]}"
          team_project_field="${TEAM_PROJECT_FIELD[$team]}"

          echo "--- Processing $team (providers: $providers_list) ---"

          # Build controller app checklist for the issue body
          CHECKLIST=""
          for provider in ${TEAM_PROVIDERS[$team]}; do
            case "$provider" in
              aws)
                CHECKLIST+="- [ ] \`cloud-provider-aws\` — updated for Kubernetes in $VERSION"$'\n'
                ;;
              azure)
                CHECKLIST+="- [ ] \`azure-cloud-controller-manager\` — updated for Kubernetes in $VERSION"$'\n'
                CHECKLIST+="- [ ] \`azure-cloud-node-manager\` — updated for Kubernetes in $VERSION"$'\n'
                ;;
              vsphere)
                CHECKLIST+="- [ ] \`cloud-provider-vsphere\` — updated for Kubernetes in $VERSION"$'\n'
                ;;
              cloud-director)
                CHECKLIST+="- [ ] \`cloud-provider-cloud-director\` — updated for Kubernetes in $VERSION"$'\n'
                ;;
            esac
          done

          ISSUE_TITLE="Controller readiness: $VERSION ($providers_list)"

          # Check for existing issue (deduplication)
          EXISTING_ISSUE=$(gh issue list --repo giantswarm/roadmap \
            --label "controller-readiness" --label "$team_label" \
            --search "$VERSION" --state open \
            --json number,title --jq ".[] | select(.title | contains(\"$VERSION\")) | .number" | head -1)

          if [[ -n "$EXISTING_ISSUE" ]]; then
            echo "Found existing issue #$EXISTING_ISSUE for $team. Skipping creation."
            ISSUE_NUMBER="$EXISTING_ISSUE"
            ISSUE_URL="https://github.com/giantswarm/roadmap/issues/$EXISTING_ISSUE"
          else
            # Create the issue
            ISSUE_BODY=$(cat <<EOF
        ## Controller Readiness for $VERSION

        The major release **$VERSION** has been created. The following cloud controller apps need new versions compatible with the Kubernetes version in this release.

        ### Apps to update

        $CHECKLIST

        ### Context

        - Release PRs in [giantswarm/releases](https://github.com/giantswarm/releases/pulls?q=is%3Apr+is%3Aopen+$VERSION)
        - Once all items are checked off and this issue is closed, the release PR will automatically receive a component bump to pick up the new controller versions.

        /cc @giantswarm/$team
        EOF
        )

            ISSUE_URL=$(gh issue create --repo giantswarm/roadmap \
              --title "$ISSUE_TITLE" \
              --body "$ISSUE_BODY" \
              --label "controller-readiness" --label "$team_label")

            ISSUE_NUMBER=$(echo "$ISSUE_URL" | grep -oE '[0-9]+$')
            echo "Created issue $ISSUE_URL"

            # Add the issue to GitHub Project #273 (Roadmap board)
            echo "Adding issue to project #273..."
            ITEM_ID=$(gh project item-add 273 --owner giantswarm --url "$ISSUE_URL" --format json 2>/dev/null | jq -r '.id' || echo "")

            if [[ -n "$ITEM_ID" && "$ITEM_ID" != "null" ]]; then
              echo "Added to project with item ID: $ITEM_ID"

              # Set Team field
              gh project item-edit --project-id 273 --id "$ITEM_ID" \
                --field-id "Team" --text "$team_project_field" 2>/dev/null || \
                echo "Warning: Could not set Team field (field may not exist or have different ID)"

              # Set Status field to Inbox
              gh project item-edit --project-id 273 --id "$ITEM_ID" \
                --field-id "Status" --single-select-option-id "Inbox" 2>/dev/null || \
                echo "Warning: Could not set Status field (field may not exist or have different ID)"
            else
              echo "Warning: Could not add issue to project #273"
            fi
          fi

          TRACKING_ROWS+="| $team | $providers_list | giantswarm/roadmap#$ISSUE_NUMBER | open |"$'\n'
        done

        # Post tracking comment on each release PR
        TRACKING_COMMENT=$(cat <<EOF
        <!-- CONTROLLER_READINESS_START -->
        ## Controller readiness tracker

        | Team | Providers | Issue | Status |
        |------|-----------|-------|--------|
        ${TRACKING_ROWS}
        <!-- CONTROLLER_READINESS_END -->
        EOF
        )

        IFS=',' read -ra PR_ARRAY <<< "$PR_NUMBERS"
        for pr_number in "${PR_ARRAY[@]}"; do
          pr_number=$(echo "$pr_number" | xargs) # trim whitespace
          if [[ -z "$pr_number" ]]; then
            continue
          fi

          echo "Posting tracking comment on PR #$pr_number..."

          # Check for existing tracking comment
          EXISTING_COMMENT_ID=$(gh api "repos/$GITHUB_REPOSITORY/issues/$pr_number/comments" \
            --jq '.[] | select(.body | contains("CONTROLLER_READINESS_START")) | .id' | head -1)

          if [[ -n "$EXISTING_COMMENT_ID" ]]; then
            echo "Updating existing tracking comment $EXISTING_COMMENT_ID on PR #$pr_number"
            gh api "repos/$GITHUB_REPOSITORY/issues/comments/$EXISTING_COMMENT_ID" \
              -X PATCH -f body="$TRACKING_COMMENT"
          else
            gh pr comment "$pr_number" --repo "$GITHUB_REPOSITORY" --body "$TRACKING_COMMENT"
          fi
        done

        echo "=== Controller readiness issue creation complete ==="
