apiVersion: release.giantswarm.io/v1alpha1
kind: Release
metadata:
  creationTimestamp: null
  name: v20.0.0-alpha1
spec:
  apps:
  - name: aws-cni
    version: 0.1.0
    componentVersion: 1.8.0
  - name: calico-policy-only
    version: 0.3.0
    componentVersion: 3.18.0
  - name: capi-node-labeler
    version: 0.3.3
  - name: cert-exporter
    version: 1.6.1
  - componentVersion: 1.3.1
    name: cert-manager
    version: 2.7.1
  - catalog: default
    name: chart-operator
    version: 2.19.0
  - name: cluster-autoscaler
    version: 1.19.3
  - componentVersion: 0.7.6
    name: external-dns
    version: 2.3.1
  - componentVersion: 4.1.0
    name: kiam
    version: 2.0.0
  - componentVersion: 1.9.7
    name: kube-state-metrics
    version: 1.3.1
  - componentVersion: 0.4.1
    name: metrics-server
    version: 1.3.0
  - name: net-exporter
    version: 1.10.1
  - componentVersion: 1.0.1
    name: node-exporter
    version: 1.7.2
  components:
  - catalog: control-plane-catalog
    name: app-operator
    releaseOperatorDeploy: false
    version: 5.2.0
  - catalog: control-plane-catalog
    name: capa-aws-cni-operator
    releaseOperatorDeploy: true
    version: 0.1.1
  - catalog: control-plane-catalog
    name: capa-iam-operator
    reference: 0.3.0
    releaseOperatorDeploy: true
    version: 0.3.0
  - catalog: control-plane-catalog
    name: cluster-api
    releaseOperatorDeploy: true
    version: 1.1.0-gsalphatest.4
  - catalog: control-plane-catalog
    name: cluster-api-provider-aws
    releaseOperatorDeploy: true
    version: 1.1.0-gsalphatest.1
  - catalog: control-plane-test-catalog
    name: policies-common
    releaseOperatorDeploy: true
    version: 0.10.0
  - catalog: control-plane-test-catalog
    name: policies-aws
    releaseOperatorDeploy: true
    version: 0.10.0
  - catalog: control-plane-catalog
    name: cluster-apps-operator
    releaseOperatorDeploy: true
    version: 0.6.1
  - catalog: control-plane-catalog
    name: kubernetes
    version: 1.19.9
  - catalog: control-plane-catalog
    name: containerlinux
    version: 2605.12.0
  - catalog: control-plane-catalog
    name: calico
    version: 3.15.3
  - catalog: control-plane-catalog
    name: etcd
    version: 3.4.14
  date: "2021-05-31T14:50:41Z"
  state: deprecated
status:
  inUse: false
  ready: false
