apiVersion: release.giantswarm.io/v1alpha1
kind: Release
metadata:
  name: v8.0.0
spec:
  state: deprecated
  date: 2019-03-21T10:00:00Z
  apps: []
  components:
  - name: azure-operator
    version: 2.3.0
  - name: cert-operator
    version: 0.1.0
  - name: chart-operator
    version: 0.5.0
  - name: cluster-operator
    version: 0.15.0
  - name: kubernetes
    version: 1.14.1
  - name: containerlinux
    version: 2023.5.0
  - name: coredns
    version: 1.5.0
  - name: calico
    version: 3.6.1
  - name: etcd
    version: 3.3.12
