cert-exporter:
  chart: "cert-exporter"
# chart-operator must be installed first so the chart CRD is
# created in the tenant cluster.
chart-operator:
  chart:     "chart-operator"
  namespace: "giantswarm"
# Upgrade force is disabled to avoid affecting customer workloads.
coredns:
  useUpgradeForce: false
net-exporter:
  chart: "net-exporter"
# Upgrade force is disabled to avoid affecting customer workloads.
nginx-ingress-controller:
  useUpgradeForce: false
