apiVersion: release.giantswarm.io/v1alpha1
kind: Release
metadata:
  name: aws-35.0.0
spec:
  apps:
  - name: aws-ebs-csi-driver
    version: 4.1.1
    dependsOn:
    - cloud-provider-aws
  - name: aws-ebs-csi-driver-servicemonitors
    version: 0.1.1
    dependsOn:
    - prometheus-operator-crd
  - name: aws-nth-bundle
    version: 1.3.0
  - name: aws-pod-identity-webhook
    version: 2.1.0
    dependsOn:
    - cert-manager
  - name: cert-exporter
    version: 2.9.16
    dependsOn:
    - kyverno-crds
  - name: cert-manager
    version: 3.10.0
    dependsOn:
    - prometheus-operator-crd
  - name: cert-manager-crossplane-resources
    catalog: cluster
    version: 0.1.0
  - name: chart-operator-extensions
    version: 1.1.3
    dependsOn:
    - prometheus-operator-crd
  - name: cilium
    version: 1.4.1
  - name: cilium-crossplane-resources
    catalog: cluster
    version: 0.2.1
  - name: cilium-servicemonitors
    version: 0.1.4
    dependsOn:
    - prometheus-operator-crd
  - name: cloud-provider-aws
    version: 2.0.0
    dependsOn:
    - vertical-pod-autoscaler-crd
  - name: cluster-autoscaler
    version: 1.24.3
    dependsOn:
    - kyverno-crds
  - name: coredns
    version: 1.29.1
    dependsOn:
    - cilium
  - name: coredns-extensions
    version: 0.1.3
    dependsOn:
    - vertical-pod-autoscaler-crd
  - name: etcd-defrag
    version: 1.2.4
    dependsOn:
    - kyverno-crds
  - name: etcd-k8s-res-count-exporter
    version: 1.10.14
    dependsOn:
    - kyverno-crds
  - name: external-dns
    version: 3.4.0
    dependsOn:
    - prometheus-operator-crd
  - name: irsa-servicemonitors
    version: 0.1.1
    dependsOn:
    - prometheus-operator-crd
  - name: k8s-audit-metrics
    version: 0.10.13
    dependsOn:
    - kyverno-crds
  - name: k8s-dns-node-cache
    version: 2.9.2
    dependsOn:
    - kyverno-crds
  - name: karpenter
    version: 2.0.0
  - name: karpenter-crossplane-resources
    version: 0.5.1
  - name: karpenter-taint-remover
    version: 1.0.2
  - name: metrics-server
    version: 2.8.0
    dependsOn:
    - kyverno-crds
  - name: net-exporter
    version: 1.23.1
    dependsOn:
    - prometheus-operator-crd
  - name: network-policies
    catalog: cluster
    version: 0.1.3
    dependsOn:
    - cilium
  - name: node-exporter
    version: 1.20.11
    dependsOn:
    - kyverno-crds
  - name: node-problem-detector
    version: 0.5.2
  - name: observability-bundle
    version: 2.6.0
    dependsOn:
    - coredns
  - name: observability-policies
    version: 0.0.4
    dependsOn:
    - kyverno-crds
  - name: priority-classes
    version: 0.3.0
  - name: prometheus-blackbox-exporter
    version: 0.5.1
    dependsOn:
    - prometheus-operator-crd
  - name: security-bundle
    catalog: giantswarm
    version: 1.17.0
    dependsOn:
    - prometheus-operator-crd
  - name: teleport-kube-agent
    version: 0.10.7
    dependsOn:
    - prometheus-operator-crd
  - name: vertical-pod-autoscaler
    version: 6.1.1
    dependsOn:
    - prometheus-operator-crd
  - name: vertical-pod-autoscaler-crd
    version: 4.1.1
  components:
  - name: cluster-aws
    catalog: cluster
    version: 7.3.0
  - name: flatcar
    version: 4459.2.3
  - name: kubernetes
    version: 1.35.1
  - name: os-tooling
    version: 1.26.4
  date: "2026-02-20T16:40:08Z"
  state: active
