apiVersion: release.giantswarm.io/v1alpha1
kind: Release
metadata:
  creationTimestamp: null
  name: v20.0.0
spec:
  apps:
  - name: calico
    version: 0.2.0
    componentVersion: 3.18.0
  - name: cert-exporter
    version: 1.6.1
  - componentVersion: 1.3.1
    name: cert-manager
    version: 2.7.1
  - catalog: default
    name: chart-operator
    version: 2.11.0-capi-1
  - name: cluster-autoscaler
    version: 1.19.3
  - componentVersion: 0.7.6
    name: external-dns
    version: 2.3.1
  - componentVersion: 3.6.0
    name: kiam
    version: 1.7.1
  - componentVersion: 1.9.7
    name: kube-state-metrics
    version: 1.3.1
  - componentVersion: 0.4.1
    name: metrics-server
    version: 1.3.0
  - name: net-exporter
    version: 1.10.1
  - componentVersion: 1.0.1
    name: node-exporter
    version: 1.7.2
  components:
  - catalog: control-plane-catalog
    name: app-operator
    reference: 4.1.0
    releaseOperatorDeploy: true
    version: 4.1.0
  - catalog: control-plane-catalog
    name: cluster-api-bootstrap-provider-kubeadm
    releaseOperatorDeploy: true
    version: 0.3.19-gs1
  - catalog: control-plane-test-catalog
    name: cluster-api-control-plane
    releaseOperatorDeploy: true
    version: 0.3.19-gs1
  - catalog: control-plane-catalog
    name: cluster-api-core
    releaseOperatorDeploy: true
    version: 0.3.19-gs1
  - catalog: control-plane-test-catalog
    name: cluster-api-provider-aws
    releaseOperatorDeploy: true
    version: 0.6.6-gs1
  - catalog: control-plane-test-catalog
    name: policies-common
    releaseOperatorDeploy: true
    version: 0.0.2
    reference: 0.0.2-07001fd57efa0a397a4aa28cf3442e4c20f4168d
  - catalog: control-plane-test-catalog
    name: policies-aws
    releaseOperatorDeploy: true
    version: 0.0.2
    reference: 0.0.2-07001fd57efa0a397a4aa28cf3442e4c20f4168d
  - catalog: control-plane-catalog
    name: cluster-apps-operator
    releaseOperatorDeploy: true
    version: 0.1.0
  - catalog: control-plane-catalog
    name: kubernetes
    version: 1.19.9
  - catalog: control-plane-catalog
    name: containerlinux
    version: 2605.12.0
  - catalog: control-plane-catalog
    name: calico
    version: 3.15.3
  - catalog: control-plane-catalog
    name: etcd
    version: 3.4.14
  date: "2021-05-31T14:50:41Z"
  state: deprecated
status:
  inUse: false
  ready: false
