apiVersion: release.giantswarm.io/v1alpha1
kind: Release
metadata:
  creationTimestamp: null
  name: v20.0.0-v1alpha3
spec:
  apps:
  - componentVersion: 3.18.0
    name: calico
    version: 0.2.0
  - name: cert-exporter
    version: 1.6.0
  - componentVersion: 1.1.0
    name: cert-manager
    version: 2.4.1
  - name: chart-operator
    version: 2.11.0-a332e330b9a1e5a12e8484038f9120f243c578fe # https://github.com/giantswarm/chart-operator/pull/721
    catalog: default-test
  - componentVersion: 0.7.6
    name: external-dns
    version: 2.1.1
  - componentVersion: 1.9.7
    name: kube-state-metrics
    version: 1.3.0
  - name: metrics-server
    version: 1.2.1
  - name: net-exporter
    version: 1.9.2
  - componentVersion: 1.0.1
    name: node-exporter
    version: 1.7.1
  - name: cluster-autoscaler
    version: 1.19.1
  - name: azure-scheduled-events
    version: 0.2.2
  components:
  - name: app-operator
    releaseOperatorDeploy: true
    version: 4.2.0
  - name: cluster-api-bootstrap-provider-kubeadm
    catalog: control-plane-test-catalog
    reference: 0.0.1-67a0501138a3b9ea7a0c7544382e1df4b9e5fc23 # https://github.com/giantswarm/cluster-api-bootstrap-provider-kubeadm-app/pull/11
    releaseOperatorDeploy: true
    version: 0.0.1
  - name: cluster-api-control-plane
    catalog: control-plane-test-catalog
    reference: 0.0.1-0cc0dbaec0bfe65d5f6fffc076a7ad38797825df
    releaseOperatorDeploy: true
    version: 0.0.1
  - name: cluster-api-core
    catalog: control-plane-test-catalog
    reference: 0.0.2-e82b31841262243b4a269d3f8e0d039caf6ce462 # https://github.com/giantswarm/cluster-api-core-app/pull/18
    releaseOperatorDeploy: true
    version: 0.0.2
  - name: cluster-api-provider-azure
    catalog: control-plane-test-catalog
    reference: 0.0.0-88681d44372633e0df259238818dbfabdeb86e09 # https://github.com/giantswarm/cluster-api-provider-azure-app/pull/10
    releaseOperatorDeploy: true
    version: 0.0.0
  - name: cluster-operator
    catalog: control-plane-test-catalog
    reference: 3.6.1-5c303d6c9b708bda6404ae2974ce4a3b3f5269b3 # https://github.com/giantswarm/cluster-operator/pull/1375
    releaseOperatorDeploy: true
    version: 3.6.2-dev
  - name: kubernetes
    version: 1.19.8
  - name: containerlinux
    version: 2605.12.0
  - name: calico
    version: 3.15.3
  - name: etcd
    version: 3.4.14
  date: "2021-03-02T14:50:41Z"
  state: active
status:
  inUse: false
  ready: false
