apiVersion: release.giantswarm.io/v1alpha1
kind: Release
metadata:
  creationTimestamp: null
  name: v15.0.0
spec:
  apps:
  - name: cert-exporter
    version: 1.8.0
  - name: chart-operator
    version: 2.19.0
  - componentVersion: 1.8.3
    name: coredns
    version: 1.6.0
  - componentVersion: 1.9.7
    name: kube-state-metrics
    version: 1.4.0
  - componentVersion: 0.4.1
    name: metrics-server
    version: 1.4.0
  - name: net-exporter
    version: 1.10.3
  - componentVersion: 1.0.1
    name: node-exporter
    version: 1.8.0
  components:
  - name: app-operator
    releaseOperatorDeploy: false
    version: 5.2.0
  - name: calico
    version: 3.19.2
  - name: cert-operator
    releaseOperatorDeploy: true
    version: 1.0.1
  - name: cluster-operator
    releaseOperatorDeploy: true
    version: 0.27.1
  - name: containerlinux
    version: 2605.12.0
  - name: etcd
    version: 3.4.16
  - name: flannel-operator
    version: 0.2.0
  - name: kubernetes
    version: 1.20.10
  - name: kvm-operator
    releaseOperatorDeploy: true
    catalog: control-plane-test-catalog
    version: 3.17.4-dev
    reference: 3.17.3-c88a065b73888059a0a2a2df7c995f3482fd68dc
  date: "2021-08-17T12:00:00Z"
  state: active
status:
  inUse: false
  ready: false
