apiVersion: release.giantswarm.io/v1alpha1
kind: Release
metadata:
  creationTimestamp: null
  name: v15.0.0
spec:
  apps:
  - name: cert-exporter
    version: 1.7.1
  - name: chart-operator
    version: 2.18.0
  - componentVersion: 1.8.3
    name: coredns
    version: 1.6.0
  - componentVersion: 1.9.7
    name: kube-state-metrics
    version: 1.3.1
  - componentVersion: 0.4.1
    name: metrics-server
    version: 1.3.0
  - name: net-exporter
    version: 1.10.2
  - componentVersion: 1.0.1
    name: node-exporter
    version: 1.7.2
  components:
  - name: app-operator
    releaseOperatorDeploy: false
    version: 5.0.0
  - name: calico
    version: 3.19.1
  - name: cert-operator
    releaseOperatorDeploy: true
    version: 1.0.1
  - name: cluster-operator
    releaseOperatorDeploy: true
    version: 0.27.1
  - name: containerlinux
    version: 2605.12.0
  - name: etcd
    version: 3.4.16
  - name: kubernetes
    version: 1.20.9
  - name: kvm-operator
    releaseOperatorDeploy: true
    catalog: control-plane-test-catalog
    version: 4.0.0-dev
    reference: 4.0.0-sha
  date: "2021-08-1T12:13:26Z"
  state: active
status:
  inUse: false
  ready: false
