- version: 1.5.0
  componentVersion: 0.29.0
  description: Upgrade to nginx-ingress-controller 0.29.0.
  kind: changed
  urls:
    - https://github.com/giantswarm/nginx-ingress-controller-app/pull/30
- version: 1.4.0
  componentVersion: 0.28.0
  description: Support overriding all nginx configmap settings.
  kind: changed
  urls:
    - https://github.com/giantswarm/nginx-ingress-controller-app/pull/26
- version: 1.3.0
  componentVersion: 0.28.0
  description: Upgrade to nginx-ingress-controller 0.28.0.
  kind: changed
  urls:
    - https://github.com/giantswarm/nginx-ingress-controller-app/pull/24
