apiVersion: release.giantswarm.io/v1alpha1
kind: Release
metadata:
  name: azure-29.5.0
spec:
  apps:
  - name: azure-cloud-controller-manager
    version: 1.29.8-gs1
    dependsOn:
    - vertical-pod-autoscaler-crd
  - name: azure-cloud-node-manager
    version: 1.29.8-gs1
    dependsOn:
    - vertical-pod-autoscaler-crd
  - name: azuredisk-csi-driver
    version: 1.30.2-gs2
    dependsOn:
    - azure-cloud-controller-manager
    - azure-cloud-node-manager
  - name: azurefile-csi-driver
    version: 1.30.2-gs1
    dependsOn:
    - azure-cloud-controller-manager
    - azure-cloud-node-manager
  - name: capi-node-labeler
    version: 0.5.0
  - name: cert-exporter
    version: 2.9.3
    dependsOn:
    - kyverno-crds
  - name: cert-manager
    version: 3.8.2
    dependsOn:
    - prometheus-operator-crd
  - name: chart-operator-extensions
    version: 1.1.2
    dependsOn:
    - prometheus-operator-crd
  - name: cilium
    version: 0.25.2
  - name: cilium-servicemonitors
    version: 0.1.2
    dependsOn:
    - prometheus-operator-crd
  - name: coredns
    version: 1.23.0
    dependsOn:
    - cilium
  - name: etcd-k8s-res-count-exporter
    version: 1.10.0
    dependsOn:
    - kyverno-crds
  - name: external-dns
    version: 3.1.0
    dependsOn:
    - prometheus-operator-crd
  - name: k8s-audit-metrics
    version: 0.10.0
    dependsOn:
    - kyverno-crds
  - name: k8s-dns-node-cache
    version: 2.8.1
    dependsOn:
    - kyverno-crds
  - name: metrics-server
    version: 2.4.2
    dependsOn:
    - kyverno-crds
  - name: net-exporter
    version: 1.21.0
    dependsOn:
    - prometheus-operator-crd
  - name: network-policies
    catalog: cluster
    version: 0.1.1
    dependsOn:
    - cilium
  - name: node-exporter
    version: 1.20.0
    dependsOn:
    - kyverno-crds
  - name: observability-bundle
    version: 1.9.0
    dependsOn:
    - coredns
  - name: observability-policies
    version: 0.0.1
    dependsOn:
    - kyverno-crds
  - name: prometheus-blackbox-exporter
    version: 0.5.0
    dependsOn:
    - prometheus-operator-crd
  - name: security-bundle
    catalog: giantswarm
    version: 1.9.1
    dependsOn:
    - prometheus-operator-crd
  - name: teleport-kube-agent
    version: 0.10.3
  - name: vertical-pod-autoscaler
    version: 5.3.1
    dependsOn:
    - prometheus-operator-crd
  - name: vertical-pod-autoscaler-crd
    version: 3.1.2
  components:
  - name: cluster-azure
    catalog: cluster
    version: 1.6.0
  - name: flatcar
    version: 4081.2.1
  - name: kubernetes
    version: 1.29.13
  - name: os-tooling
    version: 1.22.1
  date: "2025-01-27T18:00:00Z"
  state: active
