apiVersion: release.giantswarm.io/v1alpha1
kind: Release
metadata:
  name: eks-32.0.1
spec:
  apps:
  - name: aws-ebs-csi-driver
    version: 3.3.0
    dependsOn:
    - vertical-pod-autoscaler-crd
  - name: cilium
    version: 1.3.0
  - name: coredns
    version: 1.28.1
    dependsOn:
    - cilium
  - name: network-policies
    catalog: cluster
    version: 0.1.1
    dependsOn:
    - cilium
  - name: teleport-kube-agent
    version: 0.10.6
  - name: vertical-pod-autoscaler-crd
    version: 4.1.1
  components:
  - name: cluster-eks
    catalog: cluster
    version: 1.0.0
  - name: flatcar
    version: 4152.2.3
  - name: kubernetes
    version: 1.32.9
  - name: os-tooling
    version: 1.26.1
  date: "2025-11-03T09:39:39Z"
  state: active
