apiVersion: release.giantswarm.io/v1alpha1
kind: Release
metadata:
  creationTimestamp: null
  name: v20.0.0-v1alpha3
spec:
  apps:
  - name: cert-exporter
    version: 1.6.0
  - componentVersion: 1.1.0
    name: cert-manager
    version: 2.4.1
  - name: chart-operator
    version: 2.9.0
  - name: cluster-autoscaler
    version: 1.19.1
  - componentVersion: 1.6.5
    name: coredns
    version: 1.2.0
  - componentVersion: 0.7.6
    name: external-dns
    version: 2.1.1
  - componentVersion: 3.6.0
    name: kiam
    version: 1.7.0
  - componentVersion: 1.9.7
    name: kube-state-metrics
    version: 1.3.0
  - componentVersion: 0.4.1
    name: metrics-server
    version: 1.2.1
  - name: net-exporter
    version: 1.9.2
  - componentVersion: 1.0.1
    name: node-exporter
    version: 1.7.1
  components:
  - name: app-operator
    releaseOperatorDeploy: true
    version: 3.2.0
  - name: cluster-api-bootstrap-provider-kubeadm
    catalog: control-plane-test-catalog
    reference: 0.0.0-60c991fb1e848cedd7c7fc4ed9904d2613506bc7
    releaseOperatorDeploy: true
    version: 0.0.0
  - name: cluster-api-control-plane
    catalog: control-plane-test-catalog
    reference: 0.0.0-a70f54932e761e55a122417903441c2c5e992b4a
    releaseOperatorDeploy: true
    version: 0.0.0
  - name: cluster-api-core
    catalog: control-plane-test-catalog
    releaseOperatorDeploy: true
    version: 0.0.1
  - name: kubernetes
    version: 1.19.8
  - name: containerlinux
    version: 2605.12.0
  - name: calico
    version: 3.15.3
  - name: etcd
    version: 3.4.14
  date: "2021-03-02T14:50:41Z"
  state: active
status:
  inUse: false
  ready: false
