apiVersion: release.giantswarm.io/v1alpha1
kind: Release
metadata:
  annotations:
    "helm.sh/resource-policy": keep # TODO: Remove when this release is merged to master.
  creationTimestamp: null
  name: v20.0.0-v1alpha3
spec:
  apps:
  - name: calico
    version: 0.2.0
    componentVersion: 3.18.0
  - name: cert-exporter
    version: 1.6.0
  - componentVersion: 1.1.0
    name: cert-manager
    version: 2.4.1
  - name: chart-operator
    catalog: default-test
    version: 2.11.0-b3a391136adb51c5f2290a4ff2b30620c715d274 # https://github.com/giantswarm/chart-operator/pull/721
  - name: cluster-autoscaler
    version: 1.19.1
  - componentVersion: 0.7.6
    name: external-dns
    version: 2.1.1
  - componentVersion: 3.6.0
    name: kiam
    version: 1.7.0
  - componentVersion: 1.9.7
    name: kube-state-metrics
    version: 1.3.0
  - componentVersion: 0.4.1
    name: metrics-server
    version: 1.2.1
  - name: net-exporter
    version: 1.9.2
  - componentVersion: 1.0.1
    name: node-exporter
    version: 1.7.1
  components:
  - name: app-operator
    catalog: control-plane-catalog
    reference: 4.1.0
    releaseOperatorDeploy: true
    version: 4.1.0
  - name: cluster-api-bootstrap-provider-kubeadm
    catalog: control-plane-catalog
    releaseOperatorDeploy: true
    version: 0.3.14-gs1
  - name: cluster-api-control-plane
    catalog: control-plane-test-catalog
    releaseOperatorDeploy: true
    version: 0.3.14-gs1
  - name: cluster-api-core
    catalog: control-plane-catalog
    releaseOperatorDeploy: true
    version: 0.3.14-gs1
  - name: cluster-api-provider-aws
    catalog: control-plane-test-catalog
    releaseOperatorDeploy: true
    version: 0.6.5-gs1
  - name: cluster-operator
    catalog: control-plane-catalog
    releaseOperatorDeploy: true
    version: 3.7.2-capi-1
  - name: kubernetes
    version: 1.19.8
  - name: containerlinux
    version: 2605.12.0
  - name: calico
    version: 3.15.3
  - name: etcd
    version: 3.4.14
  date: "2021-03-22T14:50:41Z"
  state: active
status:
  inUse: false
  ready: false
