commonAnnotations:
  giantswarm.io/docs: https://docs.giantswarm.io/use-the-api/management-api/crd/releases.release.giantswarm.io
resources:
- v29.3.2
- v30.1.0
- v30.1.4
- v31.1.0
- v31.1.1
transformers:
- |
  apiVersion: builtin
  kind: PrefixSuffixTransformer
  metadata:
    name: release-notes
  fieldSpecs:
  - group: release.giantswarm.io
    kind: Release
    path: metadata/annotations/giantswarm.io\/release-notes
  prefix: https://github.com/giantswarm/releases/tree/master/cloud-director/v
