apiVersion: release.giantswarm.io/v1alpha1
kind: Release
metadata:
  creationTimestamp: null
  name: v8.4.1
spec:
  apps: []
  components:
  - name: app-operator
    version: 1.0.0
  - name: azure-operator
    # thiccc branch operator!
    version: 2.6.1
  - name: calico
    version: 3.8.2
  - name: cert-operator
    releaseOperatorDeploy: true
    version: 0.1.0
    reference: 0.1.0-2
  - name: chart-operator
    version: 0.7.0
  - name: cluster-operator
    # thiccc branch operator!
    version: 0.19.0
  - name: containerlinux
    version: 2135.4.0
  - name: coredns
    version: 1.6.2
  - name: etcd
    version: 3.3.13
  - name: kubernetes
    version: 1.14.6
  date: "2019-09-26T17:00:00Z"
  state: deprecated
