commonAnnotations:
  giantswarm.io/docs: https://docs.giantswarm.io/reference/cp-k8s-api/releases.release.giantswarm.io/

transformers:
  - releaseNotesTransformer.yaml

resources:
  - v9.0.0
  - v9.0.3
  - v11.2.0
  - v11.2.1
  - v11.3.0
  - v11.3.1
  - v11.3.2
