apiVersion: release.giantswarm.io/v1alpha1
kind: Release
metadata:
  name: aws-25.1.1
spec:
  apps:
  - name: aws-ebs-csi-driver
    version: 2.30.1
    dependsOn:
    - cloud-provider-aws
  - name: aws-ebs-csi-driver-servicemonitors
    version: 0.1.0
    dependsOn:
    - cert-manager
  - name: aws-pod-identity-webhook
    version: 1.16.0
    dependsOn:
    - cert-manager
  - name: capi-node-labeler
    version: 0.5.0
  - name: cert-exporter
    version: 2.9.0
    dependsOn:
    - kyverno
  - name: cert-manager
    version: 3.7.9 # aligning with Vintage, fixing bugs
    dependsOn:
    - prometheus-operator-crd
  - name: chart-operator-extensions
    version: 1.1.2
    dependsOn:
    - prometheus-operator-crd
  - name: cilium
    version: 0.25.1 # as per Cabbage request fixing bugs
  - name: cilium-crossplane-resources
    version: 0.1.0
  - name: cilium-servicemonitors
    version: 0.1.2
    dependsOn:
    - prometheus-operator-crd
  - name: cloud-provider-aws
    version: 1.25.14-gs3
    dependsOn:
    - vertical-pod-autoscaler-crd
  - name: cluster-autoscaler
    version: 1.27.3-gs9
    dependsOn:
    - kyverno
  - name: coredns
    version: 1.21.0
    dependsOn:
    - cilium
  - name: etcd-k8s-res-count-exporter
    version: 1.10.0
    dependsOn:
    - kyverno
  - name: external-dns
    version: 3.1.0
    dependsOn:
    - prometheus-operator-crd
  - name: irsa-servicemonitors
    version: 0.0.1
    dependsOn:
    - cert-manager
  - name: k8s-audit-metrics
    version: 0.9.0
    dependsOn:
    - kyverno
  - name: k8s-dns-node-cache
    version: 2.6.2
    dependsOn:
    - kyverno
  - name: metrics-server
    version: 2.4.2
    dependsOn:
    - kyverno
  - name: net-exporter
    version: 1.19.0
    dependsOn:
    - prometheus-operator-crd
  - name: network-policies
    version: 0.1.1
    catalog: cluster
    dependsOn:
    - cilium
  - name: node-exporter
    version: 1.19.0
    dependsOn:
    - kyverno
  - name: observability-bundle
    version: 1.3.4
    dependsOn:
    - coredns
  - name: prometheus-blackbox-exporter
    version: 0.4.1
    dependsOn:
    - prometheus-operator-crd
  - name: security-bundle
    version: 1.7.0
    catalog: giantswarm
    dependsOn:
    - prometheus-operator-crd
  - name: teleport-kube-agent
    version: 0.9.0
  - name: vertical-pod-autoscaler
    version: 5.2.2
    dependsOn:
    - prometheus-operator-crd
  - name: vertical-pod-autoscaler-crd
    version: 3.1.0
  components:
  - name: cluster-aws
    catalog: cluster
    version: 1.1.3
  - name: flatcar
    version: 3815.2.5 # CVEs OpenSSH fixed
  - name: flatcar-variant
    version: 1.0.0
  - name: kubernetes
    version: 1.25.16
  date: "2024-09-19T12:00:00Z"
  state: deprecated
