apiVersion: release.giantswarm.io/v1alpha1
kind: Release
metadata:
  name: eks-35.0.0
spec:
  apps:
  - name: aws-ebs-csi-driver
    version: 4.3.0
  - name: cilium
    version: 1.4.5
  - name: coredns
    version: 1.31.0
    dependsOn:
    - cilium
  - name: network-policies
    catalog: cluster
    version: 0.2.0
    dependsOn:
    - cilium
  - name: observability-bundle
    version: 2.9.1
    dependsOn:
    - coredns
  - name: teleport-kube-agent
    version: 0.11.1
    dependsOn:
    - prometheus-operator-crd
  components:
  - name: cluster-eks
    catalog: cluster
    version: 2.2.0
  - name: flatcar
    version: 4593.2.3
  - name: kubernetes
    version: 1.35.6
  - name: os-tooling
    version: 1.32.1
  date: "2026-07-01T14:31:55Z"
  state: active
