name: Create draft release

on: [push,pull_request]

jobs:
  create_draft_release:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        fetch-depth: '0'
    - name: Check gh cli
      run: which gh
    - name: Get new releases
      run: |
        for aws_release_dir in capa/*; do
          aws_release_version="$(basename $aws_release_dir)"
          echo "Found AWS release $aws_release_version"
          draft_tag_name="draft/aws/$aws_release_version"
          echo "Creating tag $draft_tag_name"
          if [ $(git tag -l "$draft_tag_name") ]; then
            echo "Found existing tag $draft_tag_name, will force-overwrite it"
          else
            echo "Tag $draft_tag_name not found, will create it"
          fi
        done
