name: Create draft release

on: [push,pull_request]

jobs:
  create_draft_release:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        fetch-depth: '0'
        fetch-tags: 'true'
    - name: Check gh cli
      run: which gh
    - name: Set up git identity
      run: |
        git config --local user.email "dev@giantswarm.io"
        git config --local user.name "taylorbot"
    - name: Get new releases
      run: |
        for aws_release_dir in capa/*; do
          aws_release_version="$(basename $aws_release_dir)"
          echo "Found AWS release $aws_release_version"
          draft_tag_name="draft/aws/$aws_release_version"
          if [ $(git tag -l "$draft_tag_name") ]; then
            echo "Found existing tag $draft_tag_name, will force-overwrite it"
            git push origin ":refs/tags/$draft_tag_name"
            git tag -fa "$draft_tag_name" -m "AWS draft release $aws_release_version"
          else
            echo "Tag $draft_tag_name not found, will create it"
            git tag -a "$draft_tag_name" -m "AWS draft release $aws_release_version"
          fi
          git push origin "$draft_tag_name"
        done
