on: pull_request

  jobs:
    createCommentWithIssueLinks:
      runs-on: ubuntu-latest
      steps:
        - name: Find linked issues
          id: find_issues
          run: |
            request_file_pattern="*/requests.yaml"
            git diff --unified=0 request_file_pattern | grep 'issue:' | grep -Eo 'https?://[^ >]+' >> links.txt
            echo ::set-output name=issues::$(cat links.txt)
           
        - name: Add comment
          uses: peter-evans/create-or-update-comment@v1
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            ```
            I found the following issues related to this PR:
            ${{ steps.find_issues.outputs.links }}
            ```
