on: pull_request
jobs:
    createCommentWithIssueLinks:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout
          uses: actions/checkout@v2
          with:
            fetch-depth: 0

        - name: Find linked issues
          id: find_issues
          run: |
            set +e
            request_file_pattern="*/requests.yaml"
            git diff --unified=0  origin/${{ github.base_ref }} HEAD $request_file_pattern | grep 'issue:' | grep -Eo 'https?://[^ >]+' >> links.txt
            retVal=$?
            echo ::set-output name=ok::'false'
            if [ $retVal -eq 0 ]; then
                echo ::set-output name=issues::$(cat links.txt)
                echo ::set-output name=ok::'true'
            fi
            exit 0

        - name: Add comment
          uses: peter-evans/create-or-update-comment@v1
          if: steps.find_issues.outputs.ok == 'true'
          with:
            issue-number: ${{ github.event.pull_request.number }}
            body: |
              I found the following issues related to this PR:
              ${{ steps.find_issues.outputs.issues }}
