name: Run Tests

on:
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
    - 'sdk/**'

  push:
    branches:
    - master
    paths:
    - 'sdk/**'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4

    - name: Run tests
      run: |
        cd sdk
        make test
