name: Run Tests

on:
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
    - 'sdk/**'

  push:
    branches:
    - master
    paths:
    - 'sdk/**'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

    - name: Set up Go
      uses: actions/setup-go@7b8cf10d4e4a01d4992d18a89f4d7dc5a3e6d6f4 # v4

    - name: Run tests
      run: |
        cd sdk
        make test
